<!-- resources/views/pdf/report.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <title>Weekly Report for Sarlini Salon</title>
    <style>
        /* Base Styles */
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: #555;
            background-color: #fafafa;
            margin: 0;
            padding: 20px;
        }
        
        /* Report Container */
        .report-wrapper {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.05);
            border-radius: 10px;
            overflow: hidden;
        }
        
        /* Header Section */
        .report-header {
            background: #f5e9e0; /* Soft peach */
            color: #6d4c41;
            padding: 30px;
            text-align: center;
            border-bottom: 1px solid #e0d3c8;
        }
        
        .report-header h2 {
            margin: 0;
            font-size: 28px;
            font-weight: 600;
        }
        
        .subtitle {
            font-size: 18px;
            margin: 10px 0 0;
            color: #8d6e63;
        }
        
        .date-range {
            font-size: 16px;
            margin: 8px 0 0;
            font-weight: 400;
            color: #a1887f;
        }
        
        /* Report Table */
        .report-table {
            width: 100%;
            border-collapse: collapse;
            border: 1px solid #e0d3c8;
        }
        
        .report-table thead {
            background: #f5e9e0; /* Matching header */
            color: #6d4c41;
        }
        
        .report-table th, 
        .report-table td {
            padding: 15px;
            text-align: left;
            border-right: 1px solid #e0d3c8; /* Column borders */
            border-bottom: 1px solid #e0d3c8;
        }
        
        .report-table th {
            font-weight: 600;
            border-bottom: 2px solid #d7ccc8;
        }
        
        .report-table tr:nth-child(even) {
            background-color: #fbf7f4; /* Very subtle stripe */
        }
        
        .report-table tr:hover {
            background-color: #f5e9e0; /* Hover effect */
        }
        
        /* Footer */
        .report-footer {
            padding: 20px;
            text-align: center;
            font-size: 14px;
            color: #a1887f;
            background: #f5e9e0;
            border-top: 1px solid #e0d3c8;
        }
        
        /* Responsive Design */
        @media (max-width: 768px) {
            .report-header {
                padding: 20px;
            }
            
            .report-header h2 {
                font-size: 24px;
            }
            
            .report-table th, 
            .report-table td {
                padding: 12px;
                font-size: 14px;
            }
        }
    </style>
</head>
<body>
    <div class="report-wrapper">
    <div class="report-header">
    <h1 class="subtitle">Weekly Report for Sarlini Salon</h1>
    <p class="date-range">Generated: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
    
    
    <table class="report-table">
    <thead>
        <tr>
            <td>Total Appointments</td>
            <td>{{ $total }}</td>
        </tr>
        <tr>
            <td>Completed Appointments</td>
            <td>{{ $completed }}</td>
        </tr>
        <tr>
            <td>Cancelled Appointments</td>
            <td>{{ $cancelled }}</td>
        </tr>
        <tr>
            <td>No-Shows</td>
            <td>{{ $noshow }}</td>
        </tr>
        <tr>
            <td>Upcoming Appointments</td>
            <td>{{ $upcoming }}</td>
        </tr>
        <tr>
            <td>Most Used Service</td>
            <td>{{ $mostUsedService }}</td>
        </tr>
    </tbody>
    </table>
    
    <div class="report-footer">
            Generated by Sarlini Admin Panel
        </div>
</body>
</html>